# Generated by Django 5.1.6 on 2025-02-20 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinique', '0002_alter_clinique_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docteur',
            fields=[
                ('docteur_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=255)),
                ('specialite', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('clinique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique.clinique')),
            ],
            options={
                'db_table': 'docteur',
            },
        ),
    ]
