# Generated by Django 5.1.6 on 2025-02-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clinique',
            table='cliniques',
        ),
    ]
